development:
  adapter: mysql2
  encoding: utf8
  database: ironman4x4_development
  username: root
  password: password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: ironman4x4_test
  username: root
  password: password
  host: localhost

# This is for local production testing/profiling. Heroku overrides this with
# it's own connection string
staging:
  adapter: mysql2
  encoding: utf8
  database: rails
  username: rails
  password: whyM1o1U8A
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: rails
  username: rails
  password: whyM1o1U8A
  host: localhost
