set :domain, '91.215.138.149'
set :deploy_to, '/var/www/ironman4x4'
set :repository, 'git@github.com:sergeychernyakov/ironman4x4.git'
set :branch, 'master'
set :user, 'deployer'
set :rails_env, 'staging'
